import { IRoleBasedVoiceChannelConnectionTrackingOrdersRepositorySymbol } from '@domain/voice-channel-connection-tracking/IRoleBasedVoiceChannelConnectionTrackingOrdersRepository';
import { IUserBasedVoiceChannelConnectionTrackingOrdersRepositorySymbol } from '@domain/voice-channel-connection-tracking/IUserBasedVoiceChannelConnectionTrackingOrdersRepository';
import { RoleBasedVoiceChannelConnectionTrackingOrdersRepository } from './RoleBasedVoiceChannelConnectionTrackingOrdersRepository';
import { UserBasedVoiceChannelConnectionTrackingOrdersRepository } from './UserBasedVoiceChannelConnectionTrackingOrdersRepository';

export const RoleBasedVoiceChannelConnectionTrackingOrdersRepositoryProvider = {
  provide: IRoleBasedVoiceChannelConnectionTrackingOrdersRepositorySymbol,
  useClass: RoleBasedVoiceChannelConnectionTrackingOrdersRepository,
};

export const UserBasedVoiceChannelConnectionTrackingOrdersRepositoryProvider = {
  provide: IUserBasedVoiceChannelConnectionTrackingOrdersRepositorySymbol,
  useClass: UserBasedVoiceChannelConnectionTrackingOrdersRepository,
};
