import { IRoleBasedVoiceChannelConnectionTrackingOrdersRepository } from 'src/domain/voice-channel-connection-tracking/IRoleBasedVoiceChannelConnectionTrackingOrdersRepository';
import { IUserBasedVoiceChannelConnectionTrackingOrdersRepository } from 'src/domain/voice-channel-connection-tracking/IUserBasedVoiceChannelConnectionTrackingOrdersRepository';
import { RoleBasedVoiceChannelConnectionTrackingOrdersRepository } from './RoleBasedVoiceChannelConnectionTrackingOrdersRepository';
import { UserBasedVoiceChannelConnectionTrackingOrdersRepository } from './UserBasedVoiceChannelConnectionTrackingOrdersRepository';

export const RoleBasedVoiceChannelConnectionTrackingOrdersRepositoryProvider = {
  provide: IRoleBasedVoiceChannelConnectionTrackingOrdersRepository,
  useClass: RoleBasedVoiceChannelConnectionTrackingOrdersRepository,
};

export const UserBasedVoiceChannelConnectionTrackingOrdersRepositoryProvider = {
  provide: IUserBasedVoiceChannelConnectionTrackingOrdersRepository,
  useClass: UserBasedVoiceChannelConnectionTrackingOrdersRepository,
};
